// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qshvplzxwejillblgqjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzaHZwbHp4d2VqaWxsYmxncWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTgwOTQsImV4cCI6MjA2MzEzNDA5NH0.KrJsSkoJ0apzGqaQb0IpFjtVG2eajxpoYnagf0PDd-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);